AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'db/schema.rb'
  TargetRubyVersion: 2.5.3
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'